[package]
name = "henka"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23.1", features = [ "derive" ] }
cgmath = "0.18.0"
env_logger = "0.11.8"
image = "0.25.9"
pollster = "0.4.0"
wgpu = "26.0.1"
wgpu_text = "26.0.0"
winit = "0.30.12"
